In [1]:
import pandas as pd,numpy as np,seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [4]:
df = sns.load_dataset("iris")
df.head(2)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [3]:
sns.get_dataset

AttributeError: module 'seaborn' has no attribute 'get_dataset'

In [5]:
df.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output = False, drop = 'first') #ohe as a machine that will learn the categories and convert them into 0s and 1s
ohe.fit_transform(df.species.to_numpy().reshape(-1,1))

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit_transform(df.species.sort_values())#one D array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output = False, drop = 'first') #ohe as a machine that will learn the categories and convert them into 0s and 1s
ohe.fit_transform(df.species.to_numpy().reshape(-1,1))#2D array

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [11]:
le.fit_transform(df.species)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [1]:
#exploring
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(dtype='int8')
oe.fit

In [ ]:
df.species = le.fit_trnasform(df.species)

In [14]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
df.iloc[:,:-1]=sc.fit_transform(df.iloc[:,:-1])
df.head(2)

   sepal_length  sepal_width  petal_length  petal_width species
0      0.222222     0.625000      0.067797     0.041667  setosa
1      0.166667     0.416667      0.067797     0.041667  setosa

In [15]:
x=df.iloc[:,:-1]
y=df.species

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=9)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(f1_score(y_pred, y_test, average='macro'))
print(classification_report(y_pred, y_test))

NameError: name 'X' is not defined

In [22]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
f1s.append(f1_score(y_pred, y_test, average='macro'))
if f1s[i] == 1:
break
   else:
    print(f1s, end=', ')
      continue


np.max(f1s)




np.argmax(f1s)

IndentationError: expected an indented block after 'if' statement on line 5 (3966033624.py, line 6)

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

for i in range(43):
    x_train, x_test, y_train, y_test = train_test_split(
        x, y,
        test_size=0.2,
        random_state=i
    )

    model = LogisticRegression()
    model.fit(x_train, y_train)

    y_pred = model.predict(x_test)

In [26]:
from sklearn.metrics import f1_score,classification_report
f1_score(y_pred,y_test,average='macro')
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.89      1.00      0.94         8
   virginica       1.00      0.92      0.96        12

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

In [30]:
f1s = []
for i in range(43):
  x_train, x_test, y_train, y_test = train_test_split(x, y,
                                                    test_size=0.2,
                                                    random_state=i)
  model = LogisticRegression()
  model.fit(x_train, y_train)
  y_pred = model.predict(x_test)
  f1s.append(f1_score(y_pred, y_test, average='macro'))
  if f1s[i] == 1:
    break
  else:
    print(f1s, end=', ')
    continue


np.max(f1s)

[0.883076923076923], [0.883076923076923, 0.8898550724637682], [0.883076923076923, 0.8898550724637682, 0.9153439153439153], [0.883076923076923, 0.8898550724637682, 0.9153439153439153, 0.9333333333333332], [0.883076923076923, 0.8898550724637682, 0.9153439153439153, 0.9333333333333332, 0.9500891265597149], [0.883076923076923, 0.8898550724637682, 0.9153439153439153, 0.9333333333333332, 0.9500891265597149, 0.9089026915113871], [0.883076923076923, 0.8898550724637682, 0.9153439153439153, 0.9333333333333332, 0.9500891265597149, 0.9089026915113871, 0.9363636363636364], [0.883076923076923, 0.8898550724637682, 0.9153439153439153, 0.9333333333333332, 0.9500891265597149, 0.9089026915113871, 0.9363636363636364, 0.7955555555555556], [0.883076923076923, 0.8898550724637682, 0.9153439153439153, 0.9333333333333332, 0.9500891265597149, 0.9089026915113871, 0.9363636363636364, 0.7955555555555556, 0.7916666666666666],

1.0

In [31]:
np.argmax(f1s)

9

In [32]:
import joblib

In [33]:
pwd

'C:\\Users\\Hani\\SAPCU5AC_HANI\\CRASH_COURSE\\BASIC'

In [34]:
joblib.dump(model,'model.joblib')
joblib.dump(sc,'scaler.joblib')
joblib.dump(le,'encoder.joblib')

['encoder.joblib']

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier

In [35]:
y_pred_dt = dt_model.predict(x_test)
print(classification_report(y_pred_dt,y_test))

NameError: name 'dt_model' is not defined